### ISSUE TITLE
Version 17 much slower than 16.4

### ISSUE THREAD

**Issue by susnux** [nzbget/nzbget#232] opened 2016-06-27 19:22 UTC
Testing the 17.0-testing-r1726 release I noticed the webui loads very slow.
But the major problem I discovered is that the download speed with v17 is around 15KiB/s, with v16.4 it downloaded with 10MiB/s.
The download speed only affects downloading the par2 files, the normal download works as expected.

If you need more debug information, please instruct me how to obtain them, then I will provide it.

**Comment by hugbug** [comment] 2016-06-27 20:16
I'm sure that's not a general issue but something very specific to your system or settings.

For the start provide some info about your system (OS, version), hardware (CPU, RAM, type of destination drive), how nzbget was installed (via official package from nzbget home page, self compiled, from another package repository), how the previous version was installed?

If everything is slow that looks like some process takes up all CPU time. That can be unrelated to nzbget, check the process manager.

**Comment by susnux** [comment] 2016-06-27 20:23
Only the start-up is very slow and the download of the par files (complete download is about 140GiB).

Both old and new versions were self compiled from source.
Flags used:

```
--enable-parcheck
--with-tlslib=OpenSSL
```

Machine:
- OS: Gentoo Linux
- Kernel: 4.4.2
- CPU: Intel Xeon L5410
- RAM: 8 GB
- Disk: normal HDD

**Comment by hugbug** [comment] 2016-06-27 20:28
About startup of webhi there were minor changes. Please test in other browsers or from other machines (tablet or phone).

Can't think of why download of par-files could be slow. May be a coincidence; is this reproducible with other downloads?

**Comment by susnux** [comment] 2016-06-27 20:31
Oh forgot to say: While downloading that par files one thread of nzbget used around 100% CPU.

**Comment by hugbug** [comment] 2016-06-28 19:03
I'm waiting for a reply to:

> Please test in other browsers or from other machines (tablet or phone).
> 
> Can't think of why download of par-files could be slow. May be a coincidence; is this reproducible with other downloads?

**Comment by hugbug** [comment] 2016-07-06 19:58
Are you waiting for my response? Because I'm waiting for yours :)

**Comment by susnux** [comment] 2016-07-06 20:14
Yes it is Browser independent.
But I think I found the reason: I have downloaded the files (90%) with the old version and then updated.
Other downloads run normal (also the pars). So it seems nzbget has checked the previously downloaded files?

**Comment by hugbug** [comment] 2016-07-07 07:16
> So it seems nzbget has checked the previously downloaded files?

No.

Well, if that occurred only for one download and isn't reproducible anymore I suspect some other process has used too much CPU at that time and everything in NZBGet was slowed down.

I'm closing the issue. Feel free to reopen if that happens again.

**Closed as completed by hugbug** 2016-07-07 07:16 UTC
Labels: support

**Comment by susnux** [comment] 2016-07-07 11:48
At the moment I can reproduce it by downloading some files.
Then start an other nzbget installation, moving files to the intermediate folder of the new nzbget installation and start downloading the rest of the files with that new installation.
Not sure if that is supposed to work but it will produce the same problem.

**Comment by hugbug** [comment] 2016-07-07 11:52
To make it clear. Some files may be slower than others, that depends on Usenet provider.

But do you have a reproducible case where v17 downloads the same slower than v16.4?
