### ISSUE TITLE
When queue is large, NZBGet service stops (Windows 10)

### ISSUE THREAD

**Issue by PearsonFlyer** [nzbget/nzbget#429] opened 2017-08-21 22:46 UTC
Whenever my queue is more than 3 or 4 items, NZBGet's service crashes on Windows 10 (Creator's update).

The only thing that shows in my log is that looks like it loses connectivity.  I'm running on an i7-4770 with 24GB RAM and an SSD drive.  If I do a couple of items at a time, no problems at all.

Here's the relevant part of my log file from the most recent crash (up and running for 2 days prior to this with no issues). At the moment, my queue is 11 deep, and my history is 548 deep.  The server IP listed here is the same machine (all services run on the same machine - radarr, sonarr, nzbget, etc.).

```
`17-8-21 18:29:56.3|Warn|DownloadMonitoringService|Unable to retrieve queue and history items from NZBget

[v2.0.0.4949] NzbDrone.Core.Download.Clients.DownloadClientUnavailableException: Unable to connect to NzbGet. Unable to connect to the remote server ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: No connection could be made because the target machine actively refused it 192.168.1.16:8800
   at System.Net.Sockets.Socket.DoConnect(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetRequestStream(TransportContext& context)
   at System.Net.HttpWebRequest.GetRequestStream()
   at NzbDrone.Common.Http.Dispatchers.ManagedHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\ManagedHttpDispatcher.cs:line 95
   at NzbDrone.Common.Http.Dispatchers.FallbackHttpDispatcher.GetResponse(HttpRequest request, CookieContainer cookies) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\Dispatchers\FallbackHttpDispatcher.cs:line 53
   at NzbDrone.Common.Http.HttpClient.ExecuteRequest(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 119
   at NzbDrone.Common.Http.HttpClient.Execute(HttpRequest request) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Common\Http\HttpClient.cs:line 55
   at NzbDrone.Core.Download.Clients.Nzbget.NzbgetProxy.ProcessRequest[T](NzbgetSettings settings, String method, Object[] parameters) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Nzbget\NzbgetProxy.cs:line 232
   --- End of inner exception stack trace ---
   at NzbDrone.Core.Download.Clients.Nzbget.NzbgetProxy.ProcessRequest[T](NzbgetSettings settings, String method, Object[] parameters) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Nzbget\NzbgetProxy.cs:line 245
   at NzbDrone.Core.Download.Clients.Nzbget.NzbgetProxy.GetGlobalStatus(NzbgetSettings settings) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Nzbget\NzbgetProxy.cs:line 125
   at NzbDrone.Core.Download.Clients.Nzbget.Nzbget.GetQueue() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Nzbget\Nzbget.cs:line 55
   at NzbDrone.Core.Download.Clients.Nzbget.Nzbget.GetItems() in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\Clients\Nzbget\Nzbget.cs:line 184
   at NzbDrone.Core.Download.TrackedDownloads.DownloadMonitoringService.ProcessClientDownloads(IDownloadClient downloadClient) in M:\BuildAgent\work\b69c1fe19bfc2c38\src\NzbDrone.Core\Download\TrackedDownloads\DownloadMonitoringService.cs:line 89
`
```

**Comment by hugbug** [comment] 2017-08-22 04:29
This log is from Sonarr, therefore not helpful.

What would help a lot is if you can install debug version of nzbget and send me memory dump and log file when it crashes. Please see https://nzbget.net/crash-dump for details.

**Comment by hugbug** [comment] 2017-08-22 04:34
Please also send me your nzbget.conf (remove logins and passwords first) to nzbget@gmail.com. Send it right now, don't wait for a crash. Thanks.

**Comment by hugbug** [comment] 2017-08-22 11:24
From your config file:

>ArticleCache=1024
ParBuffer=512

That in sum gives 1.5GB. NZBGet for Windows is compiled in 32 Bit mode and therefore can use max. 2GB RAM. Due to memory fragmentation the real maximum is usually even lower.

I think the following is hapenning: downloading and post-processing are performed at the same time (for different items). You download items consisting of large rar-files (like 500MB for BD isos or similar). In that case the article cache can use all 1024MB. If post-processing requires to repair an item it will reserve 512MB for par-buffer. If there is no unfragmented 512MB available a crash will occur.

If I have a crash dump I can verify that assumption.

I recommend to lower the both options, for example:

>ArticleCache=512
ParBuffer=128

Nzbget works effectively even with much smaller cache like 100MB when DirectWrite is active (it is by default).

In a long term I guess I should provide 64 Bit version of nzbget for Windows to let users consume all their memory (although for no performance benefits).

**Comment by PearsonFlyer** [comment] 2017-08-22 11:26
I'll make both of those changes and see what happens.  Thank you!

**Comment by hugbug** [comment] 2017-08-22 11:29
Great.
If the crashes still occur we can do the crash dump thing.

**Comment by hugbug** [comment] 2017-08-26 17:58
I assume the issue is gone away with adjusted settings.
Closing for now. Should the problem occur again please post a comment and reopen.

**Closed as completed by hugbug** 2017-08-26 17:58 UTC
