### ISSUE TITLE
unpack failed due to the PATH_SEPARATOR at the end of the unpack folder.

### ISSUE THREAD

**Issue by mbsanchez** [nzbget/nzbget#117] opened 2015-11-27 03:15 UTC
Unpack is failing on my machine due to the PATH_SEPARATOR at the end of the unpack folder. I have noticed that unrar creates the _unpack_ folder instead of _unpack folder. Also, I have debugged nzbget and I have noticed that you are adding a PATH_SEPARATOR at the end of the unpack folder. 

The command executed by the scriptcontroller is the following:

```
"D:\nzbget/unrar" "x" "-y" "-p-" "-o+" "*.rar" "D:\nzbget\downloads\completed\Cucusoft PSP Video Converter\_unpack\"
```

Perhaps, unrar is detecting _unpack\" as _unpack" (\ is seen as escape character by unrar), and for that reason it creates the _unpack_ folder instead of _unpack.

To test my theory, I have applied the next patch and now all files unpack fine.

```
 daemon/postprocess/Unpack.cpp | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/daemon/postprocess/Unpack.cpp b/daemon/postprocess/Unpack.cpp
index d944496..5158660 100644
--- a/daemon/postprocess/Unpack.cpp
+++ b/daemon/postprocess/Unpack.cpp
@@ -337,7 +337,7 @@ void UnpackController::ExecuteUnrar(const char* szPassword)
    params.push_back(strdup(m_bHasNonStdRarFiles ? "*.*" : "*.rar"));

    char szUnpackDirParam[1024];
-   snprintf(szUnpackDirParam, 1024, "%s%c", m_szUnpackDir, PATH_SEPARATOR);
+   snprintf(szUnpackDirParam, 1024, "%s", m_szUnpackDir);
    szUnpackDirParam[1024-1] = '\0';
    params.push_back(strdup(szUnpackDirParam));
```

You can see that I have removed the PATH_SEPARATOR at the end of the unpack dir.

Now the command executed by scriptcontroller is:

```
"D:\nzbget/unrar" "x" "-y" "-p-" "-o+" "*.rar" "D:\nzbget\downloads\completed\Cucusoft PSP Video Converter\_unpack"
```

**Comment by hugbug** [comment] 2015-11-27 10:41
Without trailing separator unrar fails on Linux.
Can you please test with TWO trailing separators? May be they make unrar happier.

**Comment by mbsanchez** [comment] 2015-11-27 12:14
I have tried with next code, and it works:

```
snprintf(szUnpackDirParam, 1024, "%s%c%c", m_szUnpackDir, PATH_SEPARATOR, PATH_SEPARATOR);
```

but, how about linux?

**Comment by hugbug** [comment] 2015-11-27 20:59
Can you please make tests byxecuting unrar from command prompt using the same command line as in nzbget?
It's weird for unrar to replace the trailing slash with underscore. No escaping is allowed in command line parameters.

**Comment by mbsanchez** [comment] 2015-11-28 00:03
you are right, command line escaping is not allowed on versions lower than 5.30, but on new version 5.30 it is. I have tested with unrar version 5.21 and it goes well, but with the new version 5.30, it fails. See next images:

executing unrar with only one path separator.
![unpack_path_sep_error](https://cloud.githubusercontent.com/assets/143726/11449138/50549f3e-953d-11e5-8824-c3dbbdd9da83.png)

executing unrar with two path separators
![unpack_esc_path_sep_ok](https://cloud.githubusercontent.com/assets/143726/11449139/57e1085a-953d-11e5-813d-d94c78a20918.png)

So, you need to prepare for new unrar version.

**Comment by hugbug** [comment] 2015-11-28 00:09
Thank you for testing. I'll test on Linux to see what's the best approach.

**Comment by hugbug** [comment] 2015-11-30 10:46
I cannot reproduce the problem with current unrar 5.30 release - neither through nzbget nor through command prompt.

May be it was a bug in 5.30 beta 6. Can you please test with the latest available unrar 5.30 release?

**Comment by mbsanchez** [comment] 2015-11-30 13:15
I have tried unrar v5.30 and it does not fail. Perhaps it's a bug on v5.30 beta as you said.

**Comment by hugbug** [comment] 2015-11-30 15:13
I've studied different sources on the matter and came to conclusion that ending the string with two backslashes (before quotation mark) is a good idea.
- a C/C++ program starts via main-function taking array of parameters.
- Windows is a mess and it doesn't provide a mechanism to pass multiple arguments to new processes. Instead the full command line as string is passed to CreateProcess.
- on Windows the C/C++ runtime library prepares the arguments-array by parsing the arguments from the long command line string.
- due to a need to use spaces, backslashes and quotation marks insides arguments Microsoft implemented a set of special rules how to encode these characters so that they are then interpreted correctly **by programs compiled with MS C/C++ compiler**.
- the rules used to do the command line parsing in MS compiler aren't officially documented but the independent developers have disassembled the runtime library and have described the rules in a comprehensive article - [How Command Line Parameters Are Parsed](http://www.daviddeley.com/autohotkey/parameters/parameters.htm#WINCRULESSUM).
- one of that rule says: a backslash followed with quotation mark is interpreted as quotation mark. And a logical consequence: a backslash before quotation mark must be escaped with another backslash.
- unrar implements its own command line parsing function, exactly for the reason - to interpret paths ending with backslash in a more intuitive way  - without requiring of double backslashes.
- the special command line parsing of unrar is activate via compiler DEFINE.
- there were no changes in unrar source code between 5.30 beta 6 and 5.30 release in this regard.
- my guess is the unrar beta was compiled with wrong switches where the required DEFINE wasn't active. That has been fixed in 5.30 release.
- **anyway it's advisable to double backslash before quotation mark and I'll add a fix to nzbget.**

Thank you for the report and for the tests.

**Comment by mbsanchez** [comment] 2015-11-30 15:26
Well, I'm happy of know that, I have a custom-unrar, based on unrar 5.30, which can unpacks from stdin, what is ideal for video-streaming. Perhaps I haven't enabled the requeried DEFINE, but as you said, is a good idea ending the string with two backslashes instead of one.

Thank you a lot.

**Comment by mbsanchez** [comment] 2015-11-30 15:32
I haven't saw this in the code before:

![unrar_parser](https://cloud.githubusercontent.com/assets/143726/11475838/af5080be-9751-11e5-8a33-d1ddea1a19de.png)

**Closed as completed** 2015-11-30 18:39 UTC
