### ISSUE TITLE
ncurses not found on macOS for nzbget 17.0 and HEAD

### ISSUE THREAD

**Issue by ilovezfs** [nzbget/nzbget#264] opened 2016-08-14 10:19 UTC
```
checking for ncurses... no
configure: error: "ncurses library not found"
```

For the Homebrew formula, I'm working around this by adding

```
    ENV["ncurses_CFLAGS"] = "-I/usr/include"
    ENV["ncurses_LIBS"] = "-L/usr/lib -lncurses"
```

but it would be much preferred if patching weren't needed.

Full logs: https://gist.github.com/18c66de8d8af4cc630d6d4140724bf60

**Comment by hugbug** [comment] 2016-08-14 11:36
NZBGet uses pkg-config for all required libraries.
For system not supporting pkg-config or if one of libraries doesn't have package - use extra configure-parameters as documented in [Installation on POSIX](https://github.com/nzbget/nzbget/wiki/Installation-on-POSIX), for example for ncurses:

```
--with-libcurses-includes=/path/to/curses/includes
--with-libcurses-libraries=/path/to/curses/libraries
```

**Comment by ilovezfs** [comment] 2016-08-14 11:37
The point is not to have to specify the path to something that is always going to be in the same place. The assumption that pkg-config files will be available isn't correct.

**Comment by hugbug** [comment] 2016-08-14 11:38
So what you suggest?

**Comment by ilovezfs** [comment] 2016-08-14 11:39
The simplest approach is to check for darwin. For instance,

```
$ uname -s
Darwin
```

**Comment by hugbug** [comment] 2016-08-14 11:39
> something that is always going to be in the same place

I guess you never did cross-compiling.

**Comment by ilovezfs** [comment] 2016-08-14 11:40
I'm one of the Homebrew maintainers. I've done plenty ;)

**Comment by ilovezfs** [comment] 2016-08-14 11:41
> always going to be in the same place

I mean always going to be in the same place on macOS.

**Comment by hugbug** [comment] 2016-08-14 11:42
He-he, why would you say then that nurses is always at the same place? 😄 
For me it's more often in "/build/toolchain/armel/..." or "/build/toolchain/mipsel/..." etc. and very rare in "/usr".

**Comment by ilovezfs** [comment] 2016-08-14 11:44
Here's what I shipped: https://github.com/Homebrew/homebrew-core/commit/ed93cb3504833b4e34b140bef3acef0d7945c46d

The problem is that we consider things like `--with-libcurses-libraries` and `ENV["ncurses_LIBS"]` to be patching, and like to work with upstreams to get rid of such complications whenever possible.

**Comment by ilovezfs** [comment] 2016-08-14 11:53
A more complex approach would be to vendor your own pkg-config files for macOS for libncurses. For example, https://github.com/Homebrew/brew/tree/master/Library/Homebrew/os/mac/pkgconfig/10.11

We don't do that for ncurses in particular because anything that doesn't know where to find ncurses on macOS by default is generally considered not actually to have macOS support, but you could certainly feed such a file to pkg-config when macOS is detected if all roads must go through pkg-config in your build system.

**Comment by hugbug** [comment] 2016-08-14 12:14
Even for macOS that would require the configure-script to detect wether it is running in cross-compiling or not. `uname -s` is wrong here. I can't assume in configure-script that host=target.

Previous versions of NZBGet indeed looked for libraries in system paths but that has often caused troubles during cross-compiling because the configure script may silently use system libraries instead of reporting an error. Then the compilation failed during compiling or linking anyway. A good clear error message during configure is much better in my opinion.

Modifying configure-script with macOS specific code is certainly possible but in my opinion has no real point. I'm certain no one compile nzbget for macOS on their own; they either use official app from nzbget download page or compile with homebrew. In both cases they will not face the problem, right?

I appreciate your suggestions but I think it goes beyond the utilitarian function of configure. I don't consider using of specially provided configure-parameters as patching. Those parameters are there specially to avoid hard coding for certain systems. There are many systems nzbget needs to support.

MacOS is a major system and I'm doing my best to make nzbget easy to use for Mac users; that's why there is a precompiled app on nzbget download page. If users who try to install nzbget on Mac would indeed face the problem I would certainly do adjustments to configure even if that mean special code for certain OS.

But if I understand this correctly the only user who have (had) the problem is you and you already found a solution. All other users who will compile with homebrew don't need to do any modifications right?

I'm not using homebrew, maybe I'm wrong about my assumptions. Please correct me then.

> We don't do that for ncurses in particular because anything that doesn't know where to find ncurses on macOS by default is generally considered not actually to have macOS support

I think this is a bad strategy. Writing cross-platform applications is already difficult enough. Pkg-config is supposed to help here. If you can make your platform more friendly for cross-platform apps - why not do that?

**Comment by ilovezfs** [comment] 2016-08-14 12:23
> I think this is a bad strategy. Writing cross-platform applications is already difficult enough. Pkg-config is supposed to help here. If you can make your platform more friendly for cross-platform apps - why not do that?

I would not be opposed to a pkg-config file for libncurses personally, but others would need to buy in to that.

> But if I understand this correctly the only user who have (had) the problem is you and you already found a solution.

I'll probably use your suggested configure options in lieu of the environment variables since it seems to be the least-bad-option if configure isn't going to find it itself.

One other question I have for you is regarding https://github.com/caskroom/homebrew-cask/issues/15603.

It seems to have been determined, at least at this point, that the nzbget Cask and the nzbget Homebrew formula are for different things. Is that actually accurate?

You might prefer solely distributing via Cask if they're actually the exact same thing since we're trying to deduplicate Homebrew and Cask.

**Comment by hugbug** [comment] 2016-08-14 12:41
> I'll probably use your suggested configure options in lieu of the environment variables since it seems to be the least-bad-option if configure isn't going to find it itself.

I'm not sure which one is better. "ncurses_CFLAGS" and "ncurses_LIBS" make pkg-config think that there is a package for ncurses. Looks nice for me.

> One other question I have for you is regarding cask room

Never heard about cask.

Looking at their formula - it provides a way of distribution for NZBGet.app from nzbget download page. A different thing compared to homebrew, where the program is compiled on users machine (right?).

The end result is also different: NZBGet.app is a **Mac application** with GUI whereas nzbget from homebrew is a **console program**.

In a case you don't know: NZBGet.app from nzbget download page is a Mac application which puts an icon on menubar and starts nzbget console app in the background (invisible for user). User can control the app via menubar icon and the app brings more natural feeling than a console program. At the end the app is a wrapper for the console program.

**Comment by ilovezfs** [comment] 2016-08-14 12:48
> A different thing compared to homebrew, where the program is compiled on users machine (right?).

We distribute precompiled binaries (default for users), but users can also build themselves by passing `--build-from-source`.

Yes they sound sufficiently different for the formula and cask to both exist.

If you have a chance to find a way to get it detecting the ncurses location without intervention that would be great, but if not, it'll be OK since no files actually have to be changed.

The justification is that ncurses is part of macOS supplied by Apple, but Apple does not supply a pkg-config file, so the build system should not expect to find a pkg-config file, and it's reasonable to use system default libraries when not otherwise specified. This is why virtually no formulae in homebrew core currently need ncurses location manually specified.

```
Josephs-MacBook-Pro:Formula joe$ ag ncurses|grep -v dupes|wc -l
      79
Josephs-MacBook-Pro:Formula joe$ find . | wc -l
    3597
```

**Comment by hugbug** [comment] 2016-09-18 13:03
Closing this as resolved.

**Closed as completed by hugbug** 2016-09-18 13:03 UTC
Labels: support
