### ISSUE TITLE
Checkbox at the top left of the History table

### ISSUE THREAD

**Issue by JackDandy** [nzbget/nzbget#282] opened 2016-09-16 15:47 UTC
Ref: **NZBGet 18.0-testing**

Hello,

The checkbox at the top left of the History table, the one that selects all items on the page - ah, no it actually selects all items on all the pages that you cannot even see. 

This is really bad, I just wiped and lost an entire 640 record history for an item I was investigating for an issue, all that history gone when I expected to just be deleting records on the current page. Please change this behavior to be defacto normal - i.e. to select what is currently visible on screen.

Thanks

**Comment by guaguasi** [comment] 2016-09-16 18:50
Just submitted a PR for this.  I didn't realized this myself, so thanks for bringing it up!

**Comment by hugbug** [comment] 2016-09-16 19:25
I'm sorry for the loss of your history.

However I don't think your suggestion is an improvement. I don't see why anyone would **ever** need to select all items on current page; there is no real use case for that. On the other side selecting of all items is useful. Usually you either select certain items by clicking on their checkboxes or you select all items.

The second is in particular useful in combination with search/filter functionality. For example, let's say you need all items for a certain show. You type show name in the search box and the table shows all episodes. Would you want to select all episodes on the first page shown? No. You would either select all of them or a few particular ones.

This means you suggest to remove a very useful function and replace it with a useless one.

If you need to select many items and they happen to be all on one page you can use the selection for ranges: click on first item, then shift+click on the last item.

**Comment by guaguasi** [comment] 2016-09-16 20:03
You do have a point, but I do feel that there might be use cases such as cleaning up records page by page and saving yourself a scroll and shift click. I changed the code to keep the original functionality as the default and the modifier selects only visible items for the edge cases.

**Comment by hugbug** [comment] 2016-09-16 20:07
As an alternative solution for the original problem of accidental deleting of the items: what if the pages on the pager would indicate that they have selected items? For example with the same yellow background used in the table for selected items. Would you notice that?

**Comment by JackDandy** [comment] 2016-09-16 21:52
I understand your feelings but you're missing the point - **nowhere** in ui designs does a checkbox select items that are are not visible. Therefore, complete surprise comes when NG selects all items that no app or web based selector selects. With no undo for the destructive delete operation this is a double kicker.

An example, go look at any email web app, the first app type many learn to use, it doesn't select all the items ever with that top checkbox, it selects visible records - that is the standard defacto behavior. What NG is doing is in opposition to what the user expects from learning's over years across many apps.

Now, one may agree or disagree, but regardless of opinion, there is a ui design feature here that is contrary to the overwhelming normal.  Perhaps add a warning on delete that items from pages not visible are also marked for deletion, but for the sake of someone else falling down this hole, consider a change. 

Also, to see more items to select, the drop down records per page is there, select a max. to display on a page (10, 50, 100, [500, all], etc.) with a record search filter, and then act on them all or less than. Really, to default a select to records that cannot be seen is not good.

For now, i'll remove the button locally - it's too dangerous and too easy for user error. Therefore, no, it's not its intended usefulness right now as the first time that I used it, it floored me.

**Comment by hugbug** [comment] 2016-09-16 22:55
I explained the advantages of current behavior and showed that it was carefully thought out.

Your only argument is that some other software does that in a different way. Maybe they should change their software to make it more usable.

It's not true that "select all"-function always works for visible items only. You can for example select the whole text in a text editor even on pages that are currently not visible.

This checkbox in nzbget accompanied by extensive filter capabilities is a feature for power users. I don't like the idea of removing powerful features.

**Comment by JackDandy** [comment] 2016-09-16 23:01
Yup, that is my point exactly, people have learned and expect that with a text editor "Select all" is for all text in a document, however, that is completely not the same as -select all with a checkbox- i'll say again, look at the uses of checkboxes on html pages with records. I am not saying remove the feature, you misread me, rather, refine how it the feature is deployed so that it makes sense when using it to power and normal users.

**Comment by JackDandy** [comment] 2016-09-16 23:18
Actually, yes it is true, you said my point exactly, people have learned and expect that with a text editor -_select all_\- is for all text in the current visible document - you would not expect a -_select all_\- to select text in all opened tabs. Likewise, look at specific uses of checkboxes on html pages with records, the entire scope of a checkbox -_select all_\- is within where you scroll up and down / left and right.

I am not saying remove the feature, you misread me, rather, redefine how the feature is deployed so that it makes sense when using it to both seasoned regular and power users. By default, making the existing -_select all_\- to be in line with average user expectation is a good approach, using a modifier key for non-normal selections satisfies extra creativity.

Carefully thought out things often require improvements not thought of by the architect.

**Comment by hugbug** [comment] 2016-09-16 23:35
I'm trying to refine - I've proposed a suggestion with a yellow background on pager as an indication of the scope.

I would rather remove paging altogether than change the behavior of select-all-checkbox. I'm joking, paging is needed for performance reasons.

There are more problems with the checkbox selecting on current page only:
- when you on a page with nothing selected the checkbox is shown clear as if nothing is selected. Then you select an item and use a toolbar button which now works on previously selected items too.
- there is no simple way to deselect all as you need to navigate through all pages and click on the checkbox on each page.

I understand your frustration on loosing the history. May be we can do something special to avoid such accidents - like an extra warning when trying to delete more than one page.

**Comment by guaguasi** [comment] 2016-09-19 00:03
I'm not sure I follow. 

For me, in my branch, when an item is selected, regardless of whether or not the page is visible, the master checkbox shows [-] meaning there is an item selected somewhere. I can see how highlighting the pager may increase visibility to determine where the previously selected, non visible, items are located. As far as deselecting all, you would only need to click the master checkbox. Where is the need to navigate?

The initial set of commits I made changed the default functionality to @JackDandy's expected behavior with the option to fallback to the select _everything_ if a modifier such as control was held when clicking. Both select styles would be available.

The second set of commits included swapping the functionality to keep the current method as the default with the options to select page with the modifier. I understand that changing an expected behavior of a feature can be annoying for some users. And it keeps the current functionality for mobile users.

I'm still on the fence as to which way is best.

Another idea, would be to add a 3rd level of clicking. With nothing checked, click once for page, twice for everything, three times to deselect everything. If there is already an item checked somewhere, there could be differing logic depending on whether or not the checked box is visible. If it is, first click is select page, if it isn't, select everything. That, or it could just go directly to select everything. Regardless, after everything is selected, the subsequent click would deselect it all.

**Comment by hugbug** [comment] 2016-09-19 04:40
> I'm not sure I follow.

Your PR in current state doesn't change anything for @JackDandy, it still doesn't protect user from deleting all records (unexpected behaviour for Jack).

My reply was not about your PR but about Jacks suggestion to change the checkbox behavior, a suggestion which opens other questions.

As PR goes (it current state) I honestly think it's useless in this form as it merely increase confusion.

**Comment by guaguasi** [comment] 2016-09-19 17:25
> Your PR in current state doesn't change anything for @JackDandy, it still doesn't protect user from deleting all records (unexpected behaviour for Jack).

True. but If you drop the latest commit, it would. A resulting issue would be that users expecting the existing functionality might get confused although it's not as destructive as currently. Another issue would be that mobile users wouldn't be able to use the modifier key to select everything.

> As PR goes (it current state) I honestly think it's useless in this form as it merely increase confusion.

I don't think that's entirely the case because in it's current state, there would be no change to the user experience. It would, however, be somewhat  useless in addressing the original point of this issue as people would have to know about the feature to take the debatable advantage and/or not experience the same frustration.

**Comment by hugbug** [comment] 2016-09-19 18:19
## Overview of select-all checkbox

I understand @JackDandy's concerns. However there are many things related to this checkbox.  Before the behavior can be changed all related functionality must be taken into consideration. I summarize the things involved:
1. when nothing is selected the checkbox selects all visible items on all visible pages.
2. there is a search filter at the top of the page. It may restrict the items shown in the table. The checkbox selects only items passed through the filter.
3. if any item on any visible page is selected the checkbox is shown as half-selected to indicate that fact.
4. clicking on a half-selected checkbox deselects all items on all visible pages.
5. all toolbar commands work on selected items regardless of the fact whether the items are shown on current page or on other visible page.
6. moreover, even items on invisible pages (filtered out items) are processed by toolbar commands. I'm not sure anymore if that is a good thing though.

If we change the behavior of the checkbox as Jack suggests the following questions arise:
- when should be the checkbox displayed as fully-selected: when all items on current page are selected or when all items on all visible pages are selected? It would be logical the first so that a click on a clear checkbox will change it into fully-selected state.
- there is no simple way to deselect all as you need to navigate through all pages and click on the checkbox on each page.
- what about toolbar commands: should they now work on items of current page only or on items from all pages? If they continue to work on all items (like now) the following will happen: when you on a page with nothing selected the checkbox is shown clear as if nothing were selected. Then you select an item and use a toolbar button which now works on previously selected items from other pages too. A logical consequence of the proposal would be to make all toolbar commands work on items of current page only but it reduces the usefulness of multiselect significantly.

As a whole I think we should explore other ways of protecting from accidental deletion of all items.

**Comment by guaguasi** [comment] 2016-09-20 01:42
I just noticed that in the mobile layout, the select all/everything checkbox isn't even available. That eliminates the some issues I was trying to take into consideration.

That being said. If we backtrack one commit on my branch to guaguasi/nzbget@f8920b4 so that default click is 'select page', it works as follows:
1. when nothing is selected the checkbox selects only visible items on current page. if ctrl/command is held, the checkbox selects all visible items on all visible pages.
2. _no change. still works as expected._
3. _no change. still works as expected._ **note**: if filter is applied in current develop branch, checkbox appears unselected if currently selected items are not subject to filter.
4. _no change. still works as expected_
5. _no change. still works as expected_
6. _no change. still works as expected?_ lol. I think that toolbar commands should only work within the filter (visible pages only)

> when should be the checkbox displayed as fully-selected: when all items on current page are selected or when all items on all visible pages are selected? It would be logical the first so that a click on a clear checkbox will change it into fully-selected state.

Currently, at the aforementioned commit, it displays half-selected even if the entire current page is selected implying the subsequent pages are unchecked.

> there is no simple way to deselect all as you need to navigate through all pages and click on the checkbox on each page.

Whether it's at the current HEAD (guaguasi/nzbget@83d52a5) or at the commit I've been talking about, functionality exists to deselect everything in one click from a half-selected state. The option to navigate page by page exists but is unnecessary.

> what about toolbar commands: should they now work on items of current page only or on items from all pages? `...`

I don't think that's a logical consequence at all as the point of the check boxes are to select items and the pagination for organization. If I selected items across pages, and wish to perform an action on them, the actions should be performed on said items not only on the items on the current page. 

Point 6 above actually confuses the user, aka me, because in conjunction with the note on Point 3, the implication is that the filter creates a whole new instance until unfiltered at which point they are merged. If filtered once more, they are once again separated into the new 'filtered instance'.

In defense of the current develop branch functionality, I do see more use occurring from the select everything method.

**Edit:**
Oop. There is currently a bug in my branch I found while writing this wherein this is not working as intended.

**Comment by hugbug** [comment] 2016-09-20 05:49
The **no change** at items 3-5 is what makes that PR inconsistent and that was the point of my explanation post. It is very inconveniet to click on a checkbox and not being able to actually check it. It will be either half-checked or clear. This is also explained in the second part of my post, starting with _If we change the behavior of the checkbox as Jack suggests the following questions arise:_.

**Comment by orbisvicis** [comment] 2016-11-18 20:39
I prefer the current/original behaviour (by @hugbug). There is also another inconsistency the proposed changed would have to incorporate: shift-selecting items across pages. It doesn't have anything to do with the select-all button, but it meshes well with the concept of selecting items across pages.

That said, I agree that there should be some enhanced visual feedback or warning. Perhaps:
1. Option for pop-up warning when actions are being applied to unseen items.
2. Per-page selection count in the top right page counter, I like this.

**Comment by hugbug** [comment] 2016-11-18 20:51
@orbisvicis: appreciate your feedback.

And will be glad to hear others opinion too.

**Comment by JackDandy** [comment] 2016-11-18 23:00
Yeah visual indication is all that's missing.

Taking the current "number of items shown per page" into account on a visual indicator (e.g. 70/120 history items) so ng knows that on page showing (n) items, that num items (selected(n) + selected(x)) are selected out of the current visual scope.  This indication with a "Warning: Are you sure, there are items selected out of view" dialog should be enough to prevent user error. Each pagination tab would have its own applicable numbers. The dialog would display for any operation.

**Comment by hugbug** [comment] 2016-11-21 15:02
How do you like this?

![selector-warning-1](https://cloud.githubusercontent.com/assets/3368402/20487395/6b63c8b8-b003-11e6-9391-ffd412945659.PNG)
![selector-warning-2](https://cloud.githubusercontent.com/assets/3368402/20487396/6b65feb2-b003-11e6-8770-7de915770c1c.PNG)
![selector-warning-3](https://cloud.githubusercontent.com/assets/3368402/20487394/6b631058-b003-11e6-92ed-9bc04a8bca98.PNG)


If all selected items are on the current page then the warning isn't shown.

**Comment by JackDandy** [comment] 2016-11-21 15:49
Is there any affirmation when an action is triggered, or is that still to come ? my thought is that becoming accustomed to ng means that one is faster at moving around therefore blindness to the above warning, but a dialog confirmation is something ng can also help with to mitigate that user failure

**Comment by hugbug** [comment] 2016-11-21 15:55
Confirmation dialogs extended with a warning are the next to do.

At the moment I explore the ways to indicate selection before performing actions.

It's probably hard to feel it on screenshots. I can send you changed files if you would like to try it live.

**Comment by JackDandy** [comment] 2016-11-21 16:22
No need, looking good so far and you are on direction so I prefer to wait

**Comment by orbisvicis** [comment] 2016-11-21 21:40
Not what I expected, but I do like it. It might be a little weird having the item rows change horizontally while browsing the pages or unselecting all. 

I envisioned changes to the page counter, from:

```
[<-- Prev] [1] [2] [3] [Next -->]
```

to:

```
[<-- Prev] [1 (5)] [2 (2)] [3] [Next -->]
```

Though that might consume valuable page counters.

Regarding the confirmation dialog, I'd like that to be optional, maybe even off by default. It would make the workflow not streamlined, and eventually become a hassle, I think. I probably won't use it.

**Comment by hugbug** [comment] 2016-11-21 22:37
For some reason dense stripes don't work on safari.

Hence the alternative design:

![screen shot 2016-11-21 at 23 29 21](https://cloud.githubusercontent.com/assets/3368402/20503380/890aabb8-b042-11e6-926a-5455f490dbb1.png)
![screen shot 2016-11-21 at 23 29 34](https://cloud.githubusercontent.com/assets/3368402/20503382/8936c978-b042-11e6-8127-445be1aef5be.png)
![screen shot 2016-11-21 at 23 29 41](https://cloud.githubusercontent.com/assets/3368402/20503381/8930f8ea-b042-11e6-9678-efefc38f194e.png)

**Comment by hugbug** [comment] 2016-11-21 22:41
>Regarding the confirmation dialog, I'd like that to be optional, maybe even off by default.

My plan was to extend the existing confirmation dialogs with extra warning:

![screen shot 2016-11-21 at 23 40 04](https://cloud.githubusercontent.com/assets/3368402/20503647/f0cf964a-b043-11e6-9352-c2e0a65d7f40.png)

**Comment by JackDandy** [comment] 2016-11-21 22:51
> maybe even off by default. It would make the workflow not streamlined

Yes, the point of a warning is absolutely to break the workflow and make the user pause for thought - that's why they work (mostly). Warning dialogs are never off by default, that would be terribly counter-intuitive. For example, you would not be allowed to prevent a warning for "Do you want to delete", or operations with a permanent result.  Some apps offer to select "Don't warn me again", for _some_ non-destructive operations.

Either way, the solution presented is "nicer", the challenge is making sure **not to miss any** disruptive action triggered for multiple selections everywhere - even triggers that don't currently have a dialog need one. 

Conclusion, it's a -1 here to disable warnings for any action with a non-reversible outcome.  Even if you are only saved once from yourself, you will thank that software design. Or you can cry when it's too late like I did.

**Comment by orbisvicis** [comment] 2016-11-22 02:20
>> My plan was to extend the existing confirmation dialogs with extra warning:

> Either way, the solution presented is "nicer"

Yeah, that's awesome.

**Comment by hugbug** [comment] 2016-11-22 13:20
Which one is better: warning at the top or bottom?

![delete-confirm-dialog](https://cloud.githubusercontent.com/assets/3368402/20525201/abae03c8-b0be-11e6-9f2e-a9cef8049827.PNG)

![delete-confirm-dialog-2](https://cloud.githubusercontent.com/assets/3368402/20525202/abaf0bc4-b0be-11e6-9b8b-fcf9235f1942.PNG)

**Comment by JackDandy** [comment] 2016-11-22 16:58
+1 top. reason: a warning should be the first thing your eyes zone in on

**Comment by orbisvicis** [comment] 2016-11-22 18:29
Heh, I prefer the bottom. It keeps the position of the check-boxes consistent (ie, when no warning required). Also, it is nearer the "action" button (delete), which provides stronger visual feedback. I think the first is a more natural workflow:

1. decide to delete, select how to delete, review deletion warning, press delete
2. decide to delete, review deletion warning, select how to delete, press delete

**Comment by hugbug** [comment] 2016-11-22 19:14
We need a poll.

**Comment by JackDandy** [comment] 2016-11-22 19:59
Again, the point of a warning is absolutely to disrupt what your eyes expect, so as you expect to see checkboxes, then the warning is there to disrupt that thought, therefore - you are warned - mission accomplished.  Anything that hides a warning is counter intuitive to the purpose of a warning. Choose some stuff and come close to the fire before you see a warning, or, hey I'll warn you before you (waste your time) and get near the fire ? It's not rocket science.

**Comment by hugbug** [comment] 2016-11-22 22:47
Alternative: between the question and further controls (or explanation text):

![screen shot 2016-11-22 at 23 32 06](https://cloud.githubusercontent.com/assets/3368402/20544797/ff988cd6-b10b-11e6-8e42-291deef3de31.png)

![screen shot 2016-11-22 at 23 34 53](https://cloud.githubusercontent.com/assets/3368402/20544854/5846124a-b10c-11e6-9c4c-de7dc3c2e8bc.png)

- even more disruptive, @JackDandy 😉
- notice the close button on the warning. That's the way to tell "Don't show that warning again" , @orbisvicis 😉 - for the ones whom the warning in the table is enough:

![screen shot 2016-11-22 at 23 45 28](https://cloud.githubusercontent.com/assets/3368402/20545135/cbe2c5da-b10d-11e6-91f5-34f2c6a37a3b.png)

**Comment by JackDandy** [comment] 2016-11-22 23:08
"Don't show that warning again" for a delete operation ? oh dear.

**Comment by JackDandy** [comment] 2016-11-22 23:09
"Don't show that warning again" for a delete operation ? oh dear. hug hug, com eto the gh website and read my edits, you are missing stuff when only using email.

**Comment by JackDandy** [comment] 2016-11-22 23:10
"Don't show that warning again" for a delete operation ? oh dear. hug hug, come to the gh website and read my edits, you are missing stuff when only using email. and i loathe a million posts.

**Comment by JackDandy** [comment] 2016-11-22 23:13
"Don't show that warning again" for a delete operation ? oh dear. @hugbug come to the gh website and read my edits, you are missing stuff when only using email. and i loathe a million posts.

Scenario, there is 100 history tabs, user navigates 20 tabs from the end checking items on different tabs, can the bar list which tabs have selected items? This means a search operation does not become what is needed next due to "other pages". Indeed the bar could read, "**1 selected item, 4 on tab 2, 3 others on tab 15**"

**Comment by hugbug** [comment] 2016-11-22 23:16
Don't worry, I've learned to refresh the page as you like to edit the posts :wink: 

The point is there is already one warning on the page (before you click on Delete). And once you learned what it means the second warning in the delete dialog becomes superficious.

**Comment by hugbug** [comment] 2016-11-22 23:38
>Indeed the bar could read, "1 selected item, 4 others on tab 2"

The bar is shown only if there are selected items on other pages. In most cases you select items and then perform action without scrolling to other pages. If the bar would show the total number of selected entries that brings a question - why we don't have that useful info when only items from current page are selected? (The answer is: because the bar would show and hide when the first item is selected or last deselected changing the height of the table and position of the row you just selected/deselected).

Naming other pages may make the message too long and sometimes not possible at all when a filter is active.

I agree that it may be a little weird to tell how many records are selected on other pages but not tell how many on current page. If that's an issue I would rather change the message to a more neutral "There are records selected on other pages".

**Comment by hugbug** [comment] 2016-11-23 08:10
After thinking the whole night about that extra warnings in confirmation dialogs I'm coming to conclusion they are unnecessary. How so?

The original problem described in the first post of this issue was that the user clicking on checkbox at the table header didn't expect the selection of items on other pages. Now we have the warning bar in the table and the user is informed. It's hard to miss that warning, it appears exactly at the moment user clicks on the header checkbox.

Why bringing extra warning when deleting records from download queue (not from history)? If they were deleted by mistake the nzbs can be enqueued again. The same for most other actions.

Nonetheless I'm willing to offer an extra protection for the very special case - deleting of many history records because this information has special value. Accidentally that is exactly the use case of this github issue. There will be an extra warning dialog shown after the user chooses how to delete history records. That dialog will be shown on special conditions (to define) and may look like this:

![purge-history-confirm](https://cloud.githubusercontent.com/assets/3368402/20554303/4cc1d89c-b15b-11e6-82c8-0e4f4bcde3e7.PNG)

This warning is impossible to miss and it will be shown at rare conditions preventing the learn effect. The dialog cannot be confirmed with `Enter` key since the default action (**Cancel**) closes the dialog.

**Comment by orbisvicis** [comment] 2016-11-29 16:48
> why we don't have that useful info when only items from current page are selected? (The answer is: because the bar would show and hide when the first item is selected or last deselected changing the height of the table and position of the row you just selected/deselected).

This could still happen when switching pages or deselecting all.

> for the very special case - deleting of many history records because this information has special value

Should this also apply to deleting downloads without history tracking?

> This warning is impossible to miss and it will be shown at rare conditions

Which conditions: deleting a large amount of items (>50%?) and some items are on other pages? I assume this gets shown after the initial action dialog. It would probably need to be shown for: hide record, remove record, delete download without history. And maybe when deleting hidden records, or not?

> preventing the learn effect

+1. If it does get annoying, I'll file a report to add a "don't show again" checkbox.

**Comment by hugbug** [comment] 2016-11-29 18:00
>This could still happen when switching pages or deselecting all.

That's not a problem because in that case the mouse cursor remains on the same control as opposed to clicking on a records checkbox in which case the record would jump down.

>Should this also apply to deleting downloads without history tracking?

I don't think it's necessary, the warning bar is shown and deleting of downloads isn't that critical. It is possible to find and enqueue nzbs again.

>It would probably need to be shown for: hide record, remove record, delete download without history.

It is shown when deleting from history (regardless of chosen delete option and also for deleting of hidden records).

> Which conditions: deleting a large amount of items (>50%?) and some items are on other pages?

Currently (in the latest commit): when deleting 50 or more records from history and there are selected records on other pages. I think 50 is a good threshold for an extra warning.

**Closed as completed** 2016-12-24 14:44 UTC
Labels: feedback wanted, improvement
