### ISSUE TITLE
Bug with screen messages

### ISSUE THREAD

**Issue by Panja0** [nzbget/nzbget#470] opened 2017-11-10 09:25 UTC
Using 20.0-testing-r2147 I have a weird problem with the screen messages.
I have set my limit to 1000 messages (default AFAIK) but r2147 ignores this limit.

NZBget is running on a Synology DS415+ in Docker.

<img width="424" alt="screen shot 2017-11-10 at 10 24 29" src="https://user-images.githubusercontent.com/12939350/32651461-638d2480-c601-11e7-9e09-32c47543a611.png">

**Comment by hugbug** [comment] 2017-11-10 09:28
Thanks for reporting this.

The bug was caused by #461 and is already fixed in **develop**.

**Closed as completed by hugbug** 2017-11-10 09:28 UTC
