### ISSUE TITLE
Cannot get unpack to work after upgrade to v16

### ISSUE THREAD

**Issue by rfgamaral** [nzbget/nzbget#89] opened 2015-10-12 00:15 UTC
Hi,

First of all, awesome decision on getting the source on GitHub :)

Now, what brings me here... Ever since I upgraded to the 16 version that I cannot get my downloads past the unpack step (*.rar files is what I download). I've tried to turn debug/detail log on but I can't see any extra information that would help me understand the core problem. All it says is that it "failed to unpack". That's it. But what's the reason for that?

Please, tell me exactly what you need from me (some kind of specific logs, maybe) so I can help you help me...

Not sure if it's relevant but I have NZBGet installed on a Linux system (Debian Wheezy).

**Comment by hugbug** [comment] 2015-10-12 05:44
What's the exact error message? Please post the log (via pastebin.com).

**Comment by Makakar** [comment] 2015-10-12 10:25
Hi,

I'm also facing the same issue as above.

Downloads were completing prior to updating to 16.0, download also completes successfully in another download client.

Logs don't seem to give much info, even with debug on. Download completes, no need to repair, but fails on the unpack.

Upgrade was from 15.0, upgraded via web gui.
Linux version 4.1.6-3-desktop (geeko@buildhost) (gcc version 5.1.1 20150713 [gcc-5-branch revision 225736](SUSE Linux) ) #1 SMP PREEMPT Fri Aug 28 10:59:34 UTC 2015 (d867e86)

Pastebin of log: http://pastebin.com/7vuK3DCm

**Comment by hugbug** [comment] 2015-10-12 10:53
1. Please provide the info:
   - value of option **UnrarCmd**;
   - is option **UnpackPassFile** empty?;
   - value of option **ParScan**.
2. Try setting option **UnrarCmd** to system _unrar_; that's to test if the problem is with included _unrar_. If you were already using system _unrar_ try using the included one by setting **UnrarCmd=${AppDir}/unrar**.
3. Then please install [debug version](https://github.com/nzbget/nzbget/releases/download/v16.0/nzbget-16.0-bin-linux-debug.run):
   - install it into a separate directory (by doing so you can later easily remove that test version by just deleting the directory);
   - stop your existing nzbget and start the newly installed one;
   - use web-interface -> SYSTEM -> restore setting to import your existing configuration file but select **only news servers**;
   - activate option **DebugTarget=log**, restart;
   - try one download and (if it fails) send me the log-file (compressed);
   - if it doesn't fail just write back and we'll look further.

**Comment by Makakar** [comment] 2015-10-12 12:16
Hi,

Thanks for the reply.

UnrarCmd=${AppDir}/unrar (/opt/nzbget)
UnpackPassFile is empty
ParScan is limited.

I've just tested using system unrar (UnrarCmd=unrar) and that unpacked and completed successfully.
":/ # which unrar
/usr/bin/unrar"

I've got the log file from the debug version, let me know where to send it.

**Comment by hugbug** [comment] 2015-10-12 12:53
> UnrarCmd=${AppDir}/unrar (/opt/nzbget)

Was it really set to `${AppDir}/unrar (/opt/nzbget)`? That's not a correct setting.
Please set it to `${AppDir}/unrar` and retry.

That makes me wonder why the path was changed during update, hm.

Please send the log to nzbget@gmail.com. Thanks.

**Comment by Makakar** [comment] 2015-10-12 14:59
Hi,

Sorry I meant to say it was set to ${AppDir}/unrar

The Variable ${AppDir} = /opt/nzbget, making UnrarCmd=opt/nzbget/unrar

I've dropped you the log file via email.

**Comment by rfgamaral** [comment] 2015-10-12 20:29
I can report that changing both `unrar` and `7z` to the system utilities also solved the problem for me :)

Hopefully, the logfile from @Makakar is enough for you to identify the issue and solve it.

**Comment by hugbug** [comment] 2015-10-12 21:03
Still did not found the problem.

A request to both of you:
- please post the output of command `uname -a`.
- try unpacking something from terminal using the unrar which comes with nzbget.
- set `UnrarCmd=/path/to/nzbget/unrar` to use the included unrar via full path and test.

Thanks.

**Comment by Makakar** [comment] 2015-10-13 08:21
Hi,

MEDIA02:~ # uname -a
Linux MEDIA02 4.1.6-3-desktop #1 SMP PREEMPT Fri Aug 28 10:59:34 UTC 2015 (d867e86) x86_64 x86_64 x86_64 GNU/Linux

MEDIA02:/opt/nzbget # /opt/nzbget/unrar e /windows/san/MediaStaging/Tmp/example.rar
UNRAR 5.01 freeware      Copyright (c) 1993-2013 Alexander Roshal
Illegal instruction

Running with UnrarCmd=/path/to/nzbget/unrar gives the same issue as before, failing on the unpack with no error message returned.

Changing back to system unrar allows the unpacking to complete.

I've re-installed just incase unrar that ships with nzbget was corrupted, but got the same issue.

System unrar: UNRAR 5.30 beta 3 freeware      Copyright (c) 1993-2015 Alexander Roshal
NZBGET unrar: UNRAR 5.01 freeware      Copyright (c) 1993-2013 Alexander Roshal

Let me know if you need anymore info or need me to test anything.

*Edit: As a side test, I've also moved the test file from my SAN array to the local disk, just in case. I get the same error when using the nzbget unrar file.

**Comment by hugbug** [comment] 2015-10-13 08:42
Thank you for testing. It's now clear the unrar shipped with nzbget doesn't work on your system. It works on my machine though.
- What's your exact CPU model?
- Which Linux distro you use?

I'll try other compiler settings and send you unrar-binary for test via email.

**Comment by Makakar** [comment] 2015-10-13 08:57
Hi,

CPU is AMD 955.

Linux distro is openSUSE Tumbleweed, which is the rolling openSUSE distro, currently at 13.2

As soon as I get the binary I'll give it a test.

**Comment by hugbug** [comment] 2015-10-13 09:27
@rfgamaral:
- please post the output of command `uname -a`.
- try unpacking something from terminal using the unrar which comes with nzbget.
- what's your exact CPU model?

**Comment by rfgamaral** [comment] 2015-10-14 22:51
```
amaral@ATLASBOX:/tmp$ uname -a
Linux ATLASBOX 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u4~bpo70+1 (2015-09-22) x86_64 GNU/Linux`
```

```
amaral@ATLASBOX:/tmp$ sudo unrar e example.rar

UNRAR 5.21 beta 2 freeware      Copyright (c) 1993-2015 Alexander Roshal


Extracting from example.rar

Extracting  BackPhoto.hx                                              OK
Extracting  compile.hxml                                              OK
Extracting  DS_Note.ttf                                               OK
Extracting  Gallery.hx                                                OK
Extracting  01.jpg                                                    OK
Extracting  02.jpg                                                    OK
Extracting  03.jpg                                                    OK
Extracting  04.jpg                                                    OK
Extracting  05.jpg                                                    OK
Extracting  library.xml                                               OK
Extracting  Main.hx                                                   OK
Extracting  Photo.hx                                                  OK
All OK
```

```
amaral@ATLASBOX:/tmp$ sudo /usr/share/nzbget/unrar e example.rar

UNRAR 5.01 freeware      Copyright (c) 1993-2013 Alexander Roshal
```

`AMD Athlon(tm) Dual Core Processor 4850e`

Hope this helps...

**Comment by hugbug** [comment] 2015-10-15 05:25
Yes, that confirms the issue affects certain AMD CPUs. The included unrar was compiled using extended instructions SSSE3, which older AMD CPUs don't support. This will be fixed with the next version.

**Closed as completed by hugbug** 2015-10-15 05:25 UTC
Labels: improvement
