### ISSUE TITLE
Invalid Status: 401 communication error after update from 19.1 to build 2159

### ISSUE THREAD

**Issue by gpvelzen** [nzbget/nzbget#476] opened 2017-11-15 08:48 UTC
On my Qnap (intel x64 cpu ) I have updated from 19.1 to the latest testing build.
The update runs fine, only when I try to change something and save it I get the message in the red bar above "Invalid Status: 401 communication error"

I now have downgraded to version 19.1 and everthing is fine again.

**Comment by hugbug** [comment] 2017-11-15 09:35
Can you please for a test install into a new directory to check if the new installation works fine?

See [Installation Manual](https://nzbget.net/installation-on-linux).

**Comment by gpvelzen** [comment] 2017-11-15 10:40
At first no problem (HTTP), only afther I acces my NZBget trough https the problem starts, when I go back to HTTP I have no issues.

I use a SSL cert

**Comment by hugbug** [comment] 2017-11-15 10:49
- is this a self-signed certificate?
- any errors in nzbget log?
- any errors in browser console?
- what browser do you use?
- please test with other browsers.

**Comment by gpvelzen** [comment] 2017-11-15 11:00
- Its a startcom ssl cert
- no errors in nzbget log
- no errors in browser console
- tested with IE11/EDGE/Firefox 56.0.2 all the same problem (tested with ip and dns connection)

**Comment by hugbug** [comment] 2017-11-15 11:25
- Do you connect to nzbget directly or via another server (for example nginx)?

- > when I try to change something and save it 

    Do you mean saving settings or also saving changes in download details (name, category or priority)?

- If you don't do changes does it work to some extent?
- Please test with a self-signed certificate from http://www.selfsignedcertificate.com.
- Have you tried accessing from another pc/phone/tablet?

**Comment by gpvelzen** [comment] 2017-11-15 12:06
I connect directly
changing settings and downloads
The problem is solved **not** solved by replacing the ssl cert by an official comodo cert
acces from an android 7 Phone show the same results

Edit: afther a restart nzbget works for some time.. cant say for how long
Edit2: Firefox keeps working, for IE to work again a reboot of nzbget is needed

**Comment by hugbug** [comment] 2017-12-02 17:05
I'm afraid I can't do anything about this because the issue seems to be very specific to your system.

**Comment by hugbug** [comment] 2018-01-05 15:43
Closing this with a hope the issue is fixed. If it isn't please reopen.

**Closed as completed by hugbug** 2018-01-05 15:43 UTC

**Comment by adamskoog** [comment] 2019-05-08 18:00
@hugbug I'm getting this error message in Edge. Glad for the above to know that I can use Chrome to get around it. Nzbget is running on Windows 10, I have a Linux VM running my web proxy (nginx) with a certificate from Let's Encrypt. I get this error whether trying to view it via https or http. I just updated to version 21.0 and tested again, still seeing this issue.

Using Edge and viewing the dev tools I see an error in the console:
> HTTP401: DENIED - The requested resource requires user authentication.
(XHR)POST - https://myserver.no-ip.org/nzbget/jsonrpc
