### ISSUE TITLE
Chrome on Ubuntu: Notification.show is not a function

### ISSUE THREAD

**Issue by lukyjay** [nzbget/nzbget#86] opened 2015-10-04 05:46 UTC
Hey,

When ever I make a change on NZBGet, for example pause or resume the download queue, I get an error at the top in red:

Error in http://server:6789/status.js (line 208)

Uncaught TypeError: Notification.show is not a function

I haven't been able to locate any information on google about this error.

Any ideas what's wrong?

**Comment by lukyjay** [comment] 2015-10-04 05:47
Using Ubuntu Server 15.04 64bit and NZBGet version 15.0

**Comment by hugbug** [comment] 2015-10-05 07:20
How NZBGet was installed: via installer provided on nzbget download page or otherwise?

**Comment by lukyjay** [comment] 2015-10-05 13:31
Hey, Thanks for getting back to me

I'm very sorry but I have installed a lot of applications on the server in the past few days that I cannot recall how I installed NZBget initially.

Is there any kind of trouble shooting you recommend? I prefer not to lose my current download queue as it's around 30~ days ETA at the moment (Download speeds in Australia aren't fantastic unfortunately)

**Comment by hugbug** [comment] 2015-10-05 13:37
Please try this:
- stop NZBGet;
- via terminal install NZBGet using [universal linux installer](https://github.com/nzbget/nzbget/wiki/Installation-on-Linux) into a **separate directory**;
- start installed nzbget via "/path/to/nzbget -s" directly after installing without changing any files;
- test if web interface works correctly, you'll see an empty queue but that's OK;
- after the test stop nzbget and remove the test directory, nothing from the test installation remains.

Did web ui work without errors?

**Comment by hugbug** [comment] 2015-10-15 13:46
Closing due to lack of feedback. Feel free to reopen with more info added.

**Comment by coolcow** [comment] 2016-08-17 07:15
Can easily be reproduced with this Docker-Image => https://hub.docker.com/r/linuxserver/nzbget/ (`NZBGet 17.0`) using Chrome (`Version 52.0.2743.116 - Ubuntu 64-bit`).

---

```
Error in https://nzbget.farm.lan/edit.js (line 1978)

Uncaught TypeError: Notification.show is not a function
```

---

It happens everytime something that should be notified happens  (like an accomplished download).
The error message disappears only after a manual page reload (F5).

---

No problems with the same instance in Firefox.

**Comment by hugbug** [comment] 2016-08-17 10:10
@coolcow:

Please try this:
- stop NZBGet;
- via terminal install NZBGet using [universal linux installer](https://github.com/nzbget/nzbget/wiki/Installation-on-Linux) into a **separate directory**;
- start installed nzbget via "/path/to/nzbget -s" directly after installing without changing any files;
- test if web interface works correctly, you'll see an empty queue but that's OK;
- after the test stop nzbget and remove the test directory, nothing from the test installation remains.

Did web ui work without errors?

If the same browser works when connecting to nzbget installed with official universal installer but doesn't work with nzbget from docker then we at least know the problem is in the docker image.

**Comment by coolcow** [comment] 2016-08-17 11:18
Tested with the universal linux installer exactly as suggested.

```
cd /tmp
wget -O - http://nzbget.net/info/nzbget-version-linux.json | \
sed -n "s/^.*stable-download.*: \"\(.*\)\".*/\1/p" | \
wget --no-check-certificate -i - -O nzbget-latest-bin-linux.run
sh nzbget-latest-bin-linux.run
cd nzbget
./nzbget -s
```

First, everything looks fine.

Then, set the speedlimit to a value and click "set limit":
![bildschirmfoto vom 2016-08-17 13-11-35](https://cloud.githubusercontent.com/assets/2337234/17734432/72fef0f2-647c-11e6-9932-49344d897381.png)

=> 

![bildschirmfoto vom 2016-08-17 13-12-38](https://cloud.githubusercontent.com/assets/2337234/17734441/7c699ce6-647c-11e6-9353-5827a45961e2.png)

I have no other nzbget instance installed on my PC, so i can say for sure that i am running the instance made by the universal installer.

It stills works fine with firefox, but not on chrome.

---

```
Error in http://localhost:6789/status.js (line 1479)

Uncaught TypeError: Notification.show is not a function
```

**Comment by hugbug** [comment] 2016-08-17 12:35
Thanks for testing.
Looks like the error occurs only in Chrome running on Ubuntu.
Do you have by any chance a PC or VM with Windows or Mac where you can test Chrome (connecting to the same nzbget instance)?

**Comment by coolcow** [comment] 2016-08-17 12:46
Windows 10 (VirtualBox) with Chrome `Version 49.0.2623.112 m (64-bit)`: It works ! No Error.

**Comment by coolcow** [comment] 2016-08-17 12:54
I've found a fix that works: i replaced all occurances of `Notification` with `notification` in all JavaScript files of the webui.
The notifications now appears correctly without an error (in Chrome on Windows AND Linux).

However, i think it is a bug and should be fixed and commited to the repository.

**Comment by coolcow** [comment] 2016-08-17 13:02
Maybe the fix isn't that easy. I just realized, that there are some conflicts with variables that are called `notification` too. Some further refactoring is needed.

**Comment by hugbug** [comment] 2016-08-17 13:07
`Notification` is correct, it's declared in `index.js`.

It appears there is a global [interface ](https://developer.mozilla.org/de/docs/Web/API/notification)with the same name. However variables declared in the script should have precedence when resolving names. I think that's a bug in Chrome.

Nonetheless I need to change that name as I can't count on Chrome for the fix.

Thank you very much for investigating this.

**Closed as completed** 2016-08-21 20:30 UTC
Labels: improvement

**Comment by hugbug** [comment] 2016-08-21 20:32
@coolcow:
Can you please make a test using current development version (which includes a fix)? You just need to take the newest files from "webui"-folder from repository.

**Comment by coolcow** [comment] 2016-08-21 20:51
It looks good. No error, and i see the notification now. Thx !
