### ISSUE TITLE
Cleanup happens and excludes some files

### ISSUE THREAD

**Issue by xconverge** [nzbget/nzbget#688] opened 2020-03-26 21:33 UTC
https://pastebin.com/raw/DuFTKxeV

In this example, part32 - part45 do not get cleaned up

My setup is nzbget in a docker container on linux, and the inter and maindir are remote. I suspect there is some delay somewhere and no way to pause post processing for some amount of time.

I am open to suggestions, not sure what to try next

**Comment by xconverge** [comment] 2020-03-28 17:56
Hmm I also added a debug section to Unpack.cpp

```
		RegEx regExRar(".*\\.rar$");
		RegEx regExRarMultiSeq(".*\\.[r-z][0-9][0-9]$");
		RegEx regExSevenZip(".*\\.7z$|.*\\.7z\\.[0-9]+$");
		RegEx regExSplitExt(".*\\.[a-z,0-9]{3}\\.[0-9]{3}$");

		{
			DirBrowser dir(m_destDir);
			while (const char* filename = dir.Next())
			{
					PrintMessage(Message::mkInfo, "Debug list files: %s", filename);
			}
		}

		DirBrowser dir(m_destDir);
		while (const char* filename = dir.Next())
		{
			BString<1024> fullFilename("%s%c%s", *m_destDir, PATH_SEPARATOR, filename);
```

```
Sat Mar 28 2020 10:47:00	INFO	Deleting archive files
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.par2
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part01.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part02.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part03.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part04.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part05.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part06.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part07.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part08.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part09.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part10.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part11.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part12.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part13.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part14.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part15.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part16.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part17.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part18.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part19.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part20.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part21.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part22.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part23.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part24.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part25.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part26.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part27.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part28.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part29.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part30.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part31.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part32.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part33.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part34.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part35.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part36.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part37.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part38.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part39.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part40.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part41.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part42.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part43.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part44.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part45.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part46.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part47.rar
Sat Mar 28 2020 10:47:00	INFO	Debug list files: ff35372c7dbf4fbb9155f0a339a57634.part48.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part01.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part02.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part03.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part04.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part05.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part06.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part07.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part08.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part09.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part10.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part11.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part12.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part13.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part14.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part15.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part16.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part17.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part18.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part19.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part20.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part21.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part22.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part23.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part24.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part25.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part26.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part27.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part28.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part29.rar
Sat Mar 28 2020 10:47:00	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.part30.rar
Sat Mar 28 2020 10:47:00	INFO	Unpack for ExampleFile2 successful
Sat Mar 28 2020 10:47:00	INFO	Checking renamed files for ExampleFile2
Sat Mar 28 2020 10:47:00	INFO	No renamed files found for ExampleFile2
Sat Mar 28 2020 10:47:01	INFO	Cleaning up ExampleFile2
Sat Mar 28 2020 10:47:01	INFO	Deleting file ff35372c7dbf4fbb9155f0a339a57634.par2
```

and the files are enumerated!

I will now decompose the following if statement to see if they are being skipped for some reason

```
			if (!FileSystem::DirectoryExists(fullFilename) &&
				(m_interDir || !extractedFiles.Exists(filename)) &&
				(regExRar.Match(filename) || regExSevenZip.Match(filename) ||
				 (regExRarMultiSeq.Match(filename) && FileHasRarSignature(fullFilename)) ||
				 (m_hasSplittedFiles && regExSplitExt.Match(filename) && m_joinedFiles.Exists(filename))))
```

**Comment by hugbug** [comment] 2020-03-28 18:05
Is this a reproducible issue? If it is, please send me the nzb-file to nzbget@gmail.com.

**Comment by xconverge** [comment] 2020-03-28 18:16
It happens with nearly any file I have that has more than 30 parts, this only started when I moved from windows -> docker in linux using windows shared folders as the directories

**Comment by xconverge** [comment] 2020-03-28 18:52
I accidentally re-implemented DIRBROWSER_SNAPSHOT, woops. But after reverting my changes and just enabling/defining DIRBROWSER_SNAPSHOT 1, everything works perfectly!

I suspect that as we delete files, for some reason our directory structure changes and we miss files? Note that I am not using a mac of any sort anywhere, so the criteria for setting that flag does not seem to just be mac based. The "problem" files are not even being enumerated by dir.Next() once we start deleting some files, yet they were enumerated fine prior to us starting deletion (when we took the snapshot/cached the filenames).

Would it be possible to just expose that flag as a configuration option or would you like to continue to try and root cause this directory enumeration?

**Comment by xconverge** [comment] 2020-03-28 18:58
And since it has been a few years, here is the background it seems ;)

https://forum.nzbget.net/viewtopic.php?t=1340

**Comment by xconverge** [comment] 2020-03-28 19:38
I also should note I am using alpine for my docker image, so let me try and switch over to ubuntu and see if the behavior changes. For now though, exposing that dir_snapshot variable somehow would really be great...

https://gitlab.alpinelinux.org/alpine/aports/issues/10960

**Comment by xconverge** [comment] 2020-03-31 17:50
I have switched back to windows for now to avoid this now that I know that it is readdir implementation specific. I think it would be great to somehow expose this SNAPSHOT option to users, but I understand if you don't want to complicate the settings for the application. This will also potentially eventually fix itself if alpine implements a fix, however that could take months and exposes itself in Nzbget in a quite annoying way that can be mitigated with a snapshot

**Comment by hugbug** [comment] 2020-04-04 23:34
I think a new option would make the things unnecessary complex. Maybe I should just enable the switch generally.
I thought you can compile nzbget yourself. Isn't that the case? I could build an installer with the enabled switch for you if that would help.

**Comment by xconverge** [comment] 2020-04-05 19:17
I can compile it myself, but I would prefer to use the off the shelf released version vs maintaining my own fork just for this. It probably impacts other people as well. linuxserver/docker-nzbget has 100M+ pulls it says, I have to imagine someone else is impacted by bad enumeration of directories on a remote share.

What are the cons of enabling the switch generally? I agree that a new option is not necessarily the right answer.

The proposed solution in this link could also potentially work (it is also a good description of the problem and why you need the workaround snapshot for mac)

https://support.apple.com/kb/TA21420?locale=en_US

**Comment by hugbug** [comment] 2020-04-10 11:35
I'll keep the issue open and will enable the switch generally in the next version. Although I'm not actively working on the project at the moment and can't tell when the next release will happen.

**Comment by xconverge** [comment] 2020-04-10 17:12
Thanks @hugbug, really appreciate what you have done for this project!

**Comment by g4m3r7ag** [comment] 2020-05-15 17:18
I am also experiencing what seems to be this exact problem. Is there anything I can do to resolve it in the mean time while we wait on the next release?

**Comment by xconverge** [comment] 2020-05-15 17:50
I am running into this across all of my alpinelinux docker containers. I am hoping for a resolution within the kernel vs any specific change here. There is not a current workaround that I have found in nzbget other than to compile it yourself with a certain flag set.

**Comment by g4m3r7ag** [comment] 2020-05-15 18:11
I just linked this issue in the LinuxServer Discord and asked if there's a way a tag can be created to use an Ubuntu base or similar unaffected base for their containers.

**Comment by rteegarden** [comment] 2020-05-16 19:23
I am seeing this on my Netgear ReadyNAS, only seems to be happening last month or so.  Not sure I have changed anything lately.

**Comment by g4m3r7ag** [comment] 2020-05-21 16:53
I switched to the hotio container instead of LinuxServer and that seems to have resolved the issue for anyone that comes across this.

**Comment by hugbug** [comment] 2020-05-21 17:02
I've made the snapshot dir browser behaviour the default one. That should fix the issue for all.

If someone wants to try this and need an installer please send me a note to nzbget@gmail.con with the info of your platform and CPU architecture.

Anyway this will be included in the next release.

**Closed as completed by hugbug** 2020-05-21 17:02 UTC
Labels: improvement
