### ISSUE TITLE
Folder permission issue

### ISSUE THREAD

**Issue by aureq** [nzbget/nzbget#512] opened 2018-02-24 07:01 UTC
Hi,

As user `root`, if I set `DaemonUsername` to another user (say `aureq`) and then run the command as `root` the command `nzbget -p`, folder like `InterDir`, `NzbDir`, `QueueDir` and `TempDir` are created (Ok),but the ownership belongs to `root`. This will later creates a permission issue.

**Comment by aureq** [comment] 2018-02-24 07:08
Since I can't fully test this due to #513 I've tried to launch the daemon directly from user `aureq` and the process dies silently. However, ensuring the right ownership is set, or granting the right permissions for nzbget to create the said folder, the daemon starts correctly.

**Comment by hugbug** [comment] 2018-02-24 07:15
Duplicate of #500.

**Closed as completed by hugbug** 2018-02-24 07:15 UTC
